version: '3.7'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 15432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
        postgres-network:
          aliases:
              - postgres_host

volumes:
  pgdata: {}
networks:
    postgres-network:
        name: postgres-net
        driver: bridge
